version: '3'
services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - ./.config/dev/postgres.dev.env
    networks:
      - back

  redis:
    image: 'redis:latest'
    networks:
      - back

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      back:
        aliases:
          - client

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.config/server.dev.env
    networks:
      back:
        aliases:
          - api

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - ./worker:/app
      - /app/node_modules
    env_file:
      - ./worker/.config/worker.dev.env
    networks:
      - back

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    networks:
      - front
      - back

networks:
  front:
  back:
